# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\x1a\x1bgoogle/protobuf/empty.proto\"~\n\x07Message\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\tcreate_at\x18\x04 \x01(\t\x12\x10\n\x08group_id\x18\x05 \x01(\x05\x12\x19\n\x11recipient_user_id\x18\x06 \x01(\x05\"9\n\x12\x43reateGroupRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\ngroup_name\x18\x02 \x01(\t\"\x1c\n\x08Metadata\x12\x10\n\x08metadata\x18\x01 \x01(\t\"#\n\x10ListUsersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"&\n\x11ListUsersResponse\x12\x11\n\tuser_list\x18\x01 \x01(\t\"3\n\x0e\x41\x64\x64UserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\x05\x32\xb7\x02\n\x0b\x43hatService\x12\x36\n\x0bSendMessage\x12\r.chat.Message\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\x0b\x43reateGroup\x12\x18.chat.CreateGroupRequest\x1a\x0e.chat.Metadata\"\x00\x12@\n\x0bGetListUser\x12\x16.chat.ListUsersRequest\x1a\x17.chat.ListUsersResponse\"\x00\x12\x39\n\rFetchMetadata\x12\x16.google.protobuf.Empty\x1a\x0e.chat.Metadata\"\x00\x12\x38\n\x0e\x41\x64\x64UserToGroup\x12\x14.chat.AddUserRequest\x1a\x0e.chat.Metadata\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=49
  _globals['_MESSAGE']._serialized_end=175
  _globals['_CREATEGROUPREQUEST']._serialized_start=177
  _globals['_CREATEGROUPREQUEST']._serialized_end=234
  _globals['_METADATA']._serialized_start=236
  _globals['_METADATA']._serialized_end=264
  _globals['_LISTUSERSREQUEST']._serialized_start=266
  _globals['_LISTUSERSREQUEST']._serialized_end=301
  _globals['_LISTUSERSRESPONSE']._serialized_start=303
  _globals['_LISTUSERSRESPONSE']._serialized_end=341
  _globals['_ADDUSERREQUEST']._serialized_start=343
  _globals['_ADDUSERREQUEST']._serialized_end=394
  _globals['_CHATSERVICE']._serialized_start=397
  _globals['_CHATSERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
