# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\"4\n\rSignInRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"F\n\x0eSignInResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\"4\n\rSignUpRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\x0eSignUpResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x32\xb8\x01\n\x0b\x41uthService\x12\x35\n\x06SignIn\x12\x13.auth.SignInRequest\x1a\x14.auth.SignInResponse\"\x00\x12\x35\n\x06SignUp\x12\x13.auth.SignUpRequest\x1a\x14.auth.SignUpResponse\"\x00\x12;\n\x07SignOut\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIGNINREQUEST']._serialized_start=49
  _globals['_SIGNINREQUEST']._serialized_end=101
  _globals['_SIGNINRESPONSE']._serialized_start=103
  _globals['_SIGNINRESPONSE']._serialized_end=173
  _globals['_SIGNUPREQUEST']._serialized_start=175
  _globals['_SIGNUPREQUEST']._serialized_end=227
  _globals['_SIGNUPRESPONSE']._serialized_start=229
  _globals['_SIGNUPRESPONSE']._serialized_end=262
  _globals['_AUTHSERVICE']._serialized_start=265
  _globals['_AUTHSERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
